/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courseregistrationsystem;

/**
 *
 * @author HoaNguyen
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnDSGiaoVu = new javax.swing.JButton();
        btnQuanLyMonHoc = new javax.swing.JButton();
        btnQuanLyHocKi = new javax.swing.JButton();
        btnQuanLyLopHoc = new javax.swing.JButton();
        btnQuanLyThoiGianDangKi = new javax.swing.JButton();
        btnQuanLyHocPhan = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        account = new javax.swing.JMenu();
        menuAccount = new javax.swing.JMenuItem();
        menuChangPass = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Danh sách chức năng");

        btnDSGiaoVu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDSGiaoVu.setText("Danh sách giáo vụ");
        btnDSGiaoVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSGiaoVuActionPerformed(evt);
            }
        });

        btnQuanLyMonHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuanLyMonHoc.setText("Quản lý môn học");
        btnQuanLyMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyMonHocActionPerformed(evt);
            }
        });

        btnQuanLyHocKi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuanLyHocKi.setText("Quản lý học kì");
        btnQuanLyHocKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyHocKiActionPerformed(evt);
            }
        });

        btnQuanLyLopHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuanLyLopHoc.setText("Quản lý lớp học");
        btnQuanLyLopHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyLopHocActionPerformed(evt);
            }
        });

        btnQuanLyThoiGianDangKi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuanLyThoiGianDangKi.setText("Quản lý thời gian đăng kí");
        btnQuanLyThoiGianDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyThoiGianDangKiActionPerformed(evt);
            }
        });

        btnQuanLyHocPhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuanLyHocPhan.setText("Quản lý lớp học");
        btnQuanLyHocPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyHocPhanActionPerformed(evt);
            }
        });

        account.setText("Tài khoản");

        menuAccount.setText("Thông tin tài khoản");
        menuAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAccountActionPerformed(evt);
            }
        });
        account.add(menuAccount);

        menuChangPass.setText("Thay đổi mật khẩu");
        menuChangPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChangPassActionPerformed(evt);
            }
        });
        account.add(menuChangPass);

        menuLogout.setText("Đăng xuất");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        account.add(menuLogout);

        jMenuBar1.add(account);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuanLyMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDSGiaoVu, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLyThoiGianDangKi))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnQuanLyLopHoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLyHocKi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLyHocPhan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDSGiaoVu)
                    .addComponent(btnQuanLyHocKi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuanLyMonHoc)
                    .addComponent(btnQuanLyLopHoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuanLyHocPhan)
                    .addComponent(btnQuanLyThoiGianDangKi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDSGiaoVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSGiaoVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDSGiaoVuActionPerformed

    private void btnQuanLyMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyMonHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyMonHocActionPerformed

    private void btnQuanLyHocKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyHocKiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyHocKiActionPerformed

    private void btnQuanLyLopHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyLopHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyLopHocActionPerformed

    private void btnQuanLyThoiGianDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyThoiGianDangKiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyThoiGianDangKiActionPerformed

    private void menuAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAccountActionPerformed

    private void menuChangPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChangPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuChangPassActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void btnQuanLyHocPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyHocPhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyHocPhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu account;
    private javax.swing.JButton btnDSGiaoVu;
    private javax.swing.JButton btnQuanLyHocKi;
    private javax.swing.JButton btnQuanLyHocPhan;
    private javax.swing.JButton btnQuanLyLopHoc;
    private javax.swing.JButton btnQuanLyMonHoc;
    private javax.swing.JButton btnQuanLyThoiGianDangKi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAccount;
    private javax.swing.JMenuItem menuChangPass;
    private javax.swing.JMenuItem menuLogout;
    // End of variables declaration//GEN-END:variables
}
